FROM node:12.16.3

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies: both package.json AND package-lock.json are copied
COPY package*.json ./

#RUN npm install
# In production
RUN npm ci --only=production

# Bundle app source
COPY . ./

EXPOSE 3006
CMD [ "node", "index.js" ]