FROM node:12.18.2

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies: both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm ci --only=production

# Bundle app source
COPY . ./

#Build CSS Dependencies
RUN npm run build

EXPOSE 3006

CMD [ "npm", "start" ]